services:
  - type: web
    name: doghub-backend
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
    # Add your environment variables in the Render dashboard
    # MONGODB_URI, JWT secrets, Cloudinary, Razorpay etc.